services:
  - type: web
    name: sudgen-backend
    env: python
    buildCommand: pip install -r requirements.txt
    # Updated start command with explicit host and port binding
    startCommand: |
      gunicorn main:app \
        --worker-class uvicorn.workers.UvicornWorker \
        --bind 0.0.0.0:$PORT \
        --workers 4 \
        --access-logfile - \
        --error-logfile - \
        --log-level info
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: FRONTEND_URL
        value: "https://your-frontend-url.com"
    healthCheckPath: /
