services:
  - type: web
    name: sudgen-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: FRONTEND_URL
        value: https://your-frontend-url.com
